flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: https://github.com/cspollard/histogram-extras.git
    commit: 48d1cc76d77bfce156a603e21384e38201b76fd2
  extra-dep: true

- location:
    git: https://github.com/cspollard/variation.git
    commit: 5ec69558ad1e8bc4f94510f851f24671967fc922
  extra-dep: true

- location:
    git: https://github.com/cspollard/hhep.git
    commit: 62732621d721b5522248932193a41dd7246fec01
  extra-dep: true

extra-deps:
- cereal-text-0.1.0.2
- histogram-fill-cereal-0.6.2.0
resolver: lts-9.0
