flags: {}
extra-package-dbs: []
packages:
- '.'
- '../variation.git'
- '../histogram-extras.git'
- '../moore.git'
- '../hhep.git'

extra-deps:        
  - extensible-0.5.1
  - membership-0

resolver: lts-14.7
