flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: https://github.com/cspollard/histogram-extras.git
    commit: 131989aefa7ec40f081e9fbde07c863849e38a4a
  extra-dep: true

- location:
    git: https://github.com/cspollard/variation.git
    commit: 1659fc5412c66b31c0b8f0a36cc75734a9c96454
  extra-dep: true

- location:
    git: https://github.com/cspollard/hhep.git
    commit: 62732621d721b5522248932193a41dd7246fec01
  extra-dep: true

extra-deps:
- cereal-text-0.1.0.2
- histogram-fill-cereal-0.6.2.0
resolver: lts-9.0
