flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: https://github.com/cspollard/histogram-extras.git
    commit: 853d39145758abb6877c8733b4d78422da0d6d8f
  extra-dep: true

- location:
    git: https://github.com/cspollard/variation.git
    commit: 1659fc5412c66b31c0b8f0a36cc75734a9c96454
  extra-dep: true

- location:
    git: https://github.com/cspollard/hhep.git
    commit: 2aae98b10e637f6c52a2b73b6725d7c54cc69942
  extra-dep: true

extra-deps:
- cereal-text-0.1.0.2
- histogram-fill-cereal-0.6.2.0
resolver: lts-8.17
